# Generated by Django 3.0.5 on 2020-05-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('furn', '0002_user_detail_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.SlugField(unique=True)),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('crossed_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('furniture_type', models.CharField(choices=[('a', 'Almirah'), ('b', 'Bed'), ('ch', 'Chair'), ('cl', 'Closet'), ('l', 'Lamp'), ('m', 'Mattress'), ('s', 'Sofa'), ('t', 'Table')], max_length=8)),
                ('length', models.IntegerField(default=0)),
                ('breadth', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
