# Generated by Django 3.0.5 on 2020-05-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0002_user_detail_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('crossed_price', models.IntegerField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('furniture_type', models.CharField(choices=[('a', 'Almirah'), ('b', 'Bed'), ('ch', 'Chair'), ('cl', 'Closet'), ('l', 'Lamp'), ('m', 'Mattress'), ('s', 'Sofa'), ('t', 'Table')], max_length=8)),
                ('images', models.ImageField(upload_to='images_directory_path')),
                ('length', models.IntegerField(default=0)),
                ('breadth', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
            ],
        ),
    ]
