# Generated by Django 3.0.5 on 2020-05-02 07:26

from django.db import migrations, models
import furn.models.product_model


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_product_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_upload',
            name='images',
            field=models.ImageField(upload_to=furn.models.product_model.images_directory_path),
        ),
    ]
