# Generated by Django 3.0.5 on 2020-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0003_image_product_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='track_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=10, null=True)),
                ('order_id', models.CharField(max_length=10)),
            ],
        ),
    ]
