# Generated by Django 3.0.5 on 2020-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0004_track_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
            ],
        ),
    ]
