# Generated by Django 3.0.5 on 2020-05-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn', '0010_auto_20200506_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
